name: Deploy with PM2

on:
  push:
    branches:
      - main
      - Khiem

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Add environment variables
        run: 
          echo "DATABASE_URL=${{ secrets.DB_URL }}" >> .env
          echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}" >> .env
          echo "REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}" >> .env
          echo "WEATHERAPI_KEY=${{ secrets.WEATHERAPI_KEY }}" >> .env
          echo "AMADEUS_KEY=${{ secrets.AMADEUS_KEY }}" >> .env
          echo "AMADEUS_SECRET=${{ secrets.AMADEUS_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env

      - name: Install dependencies
        run: npm install

      - name: Setup Prisma
        run: npx prisma generate

      - name: Build project
        run: NODE_OPTIONS="--max-old-space-size=4096" npm run build

      - name: Install PM2
        run: npm install -g pm2

      - name: Restart with PM2
        run: |
          if pm2 describe fava-be > /dev/null; then
          pm2 delete fava-be
          fi  
          pm2 start dist/main.js --name "fava-be" # Adjust the entry point to your project's start file
          pm2 save # Save the PM2 process list

      - name: Update Render environment variables
        if: github.ref == 'refs/heads/main' && success()
        env:
          RENDER_API_KEY: rnd_N1PUgoL5jtdxAhupqET04kN0MZIG
          DB_URL: ${{ secrets.DB_URL }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
          AMADEUS_KEY: ${{ secrets.AMADEUS_KEY }}
          AMADEUS_SECRET: ${{ secrets.AMADEUS_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          response=$(curl --request PUT \
          --url https://api.render.com/v1/env-groups/evg-d0of5vqdbo4c73ern210/env-vars/DB_URL \
          --header 'accept: application/json' \
          --header "authorization: Bearer ${RENDER_API_KEY}" \
          --header 'content-type: application/json' \
          --data "{\"value\":\"${DB_URL}\"}")

          echo "HTTP Response Code: $response"

          response=$(curl --request PUT \
          --url https://api.render.com/v1/env-groups/evg-d0of5vqdbo4c73ern210/env-vars/ACCESS_SECRET \
          --header 'accept: application/json' \
          --header "authorization: Bearer ${RENDER_API_KEY}" \
          --header 'content-type: application/json' \
          --data "{\"value\":\"${ACCESS_SECRET}\"}")

          echo "HTTP Response Code: $response"

          response=$(curl --request PUT \
          --url https://api.render.com/v1/env-groups/evg-d0of5vqdbo4c73ern210/env-vars/REFRESH_SECRET \
          --header 'accept: application/json' \
          --header "authorization: Bearer ${RENDER_API_KEY}" \
          --header 'content-type: application/json' \
          --data "{\"value\":\"${REFRESH_SECRET}\"}")

          echo "HTTP Response Code: $response"

          response=$(curl --request PUT \
          --url https://api.render.com/v1/env-groups/evg-d0of5vqdbo4c73ern210/env-vars/WEATHERAPI_KEY \
          --header 'accept: application/json' \
          --header "authorization: Bearer ${RENDER_API_KEY}" \
          --header 'content-type: application/json' \
          --data "{\"value\":\"${WEATHERAPI_KEY}\"}")

          echo "HTTP Response Code: $response"

          response=$(curl --request PUT \
          --url https://api.render.com/v1/env-groups/evg-d0of5vqdbo4c73ern210/env-vars/AMADEUS_KEY \
          --header 'accept: application/json' \
          --header "authorization: Bearer ${RENDER_API_KEY}" \
          --header 'content-type: application/json' \
          --data "{\"value\":\"${AMADEUS_KEY}\"}")

          echo "HTTP Response Code: $response"

          response=$(curl --request PUT \
          --url https://api.render.com/v1/env-groups/evg-d0of5vqdbo4c73ern210/env-vars/AMADEUS_SECRET \
          --header 'accept: application/json' \
          --header "authorization: Bearer ${RENDER_API_KEY}" \
          --header 'content-type: application/json' \
          --data "{\"value\":\"${AMADEUS_SECRET}\"}")

          echo "HTTP Response Code: $response"

          response=$(curl --request PUT \
          --url https://api.render.com/v1/env-groups/evg-d0of5vqdbo4c73ern210/env-vars/PORT \
          --header 'accept: application/json' \
          --header "authorization: Bearer ${RENDER_API_KEY}" \
          --header 'content-type: application/json' \
          --data "{\"value\":\"${PORT}\"}")

          echo "HTTP Response Code: $response"

      - name: Trigger Render Deployment
        if: github.ref == 'refs/heads/main' && success()
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"