name: Deploy with PM2

on:
  push:
    branches:
      - main
      - Khiem

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Add environment variables
        run: 
          echo "DATABASE_URL=${{ secrets.DB_URL }}" >> .env
          echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}" >> .env
          echo "REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}" >> .env
          echo "WEATHERAPI_KEY=${{ secrets.WEATHERAPI_KEY }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env

      - name: Install dependencies
        run: npm install

      - name: Setup Prisma
        run: npx prisma generate

      - name: Build project
        run: NODE_OPTIONS="--max-old-space-size=4096" npm run build

      - name: Install PM2
        run: npm install -g pm2

      - name: Restart with PM2
        run: |
          if pm2 describe fava-be > /dev/null; then
          pm2 delete fava-be
          fi  
          pm2 start dist/main.js --name "fava-be" # Adjust the entry point to your project's start file
          pm2 save # Save the PM2 process list

      - name: Update Render environment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          SERVICE_ID=${{ secrets.SERVICE_ID }}

          curl -X PATCH "https://api.render.com/v1/services/$SERVICE_ID/env-vars" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "envVars": [
              { "key": "DB_URL", "value": "'"${{ secrets.DB_URL }}"'", "serviceId": "'"$SERVICE_ID"'" },
              { "key": "ACCESS_SECRET", "value": "'"${{ secrets.ACCESS_SECRET }}"'", "serviceId": "'"$SERVICE_ID"'" },
              { "key": "REFRESH_SECRET", "value": "'"${{ secrets.REFRESH_SECRET }}"'", "serviceId": "'"$SERVICE_ID"'" },
              { "key": "WEATHERAPI_KEY", "value": "'"${{ secrets.WEATHERAPI_KEY }}"'", "serviceId": "'"$SERVICE_ID"'" },
              { "key": "PORT", "value": "'"${{ secrets.PORT }}"'", "serviceId": "'"$SERVICE_ID"'" }
            ]
          }'

      - name: Trigger Render Deployment
        if: github.ref == 'refs/heads/main' && success()
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"